### ISSUE TITLE
[Bug] Raid timeline says "dropped" for picked up items

### ISSUE THREAD

**Issue by Criptc** [ekky-llc/spt-raid-review#15]
the raid time lines says that you dropped items when you actually picked it up, making it hard to tell what you picked up and dropped

**Comment by christopher-talke** [comment]
Fixed this in v0.0.3; the loot timeline needs way more work and refactoring so I'm keeping this guy open.

**Comment by christopher-talke** [comment]
Fixed in dev branch, closing issue, will be in next patch.
