### ISSUE TITLE
[Bug] Reloading a guns mag counts as dropping it

### ISSUE THREAD

**Issue by Criptc** [ekky-llc/spt-raid-review#16]
when you put more bullets into a mag, it counts as dropping the mag

**Comment by christopher-talke** [comment]
Interesting, I'll see how I can account for that behaviour.

**Comment by christopher-talke** [comment]
Fixed this for packing magazines in dev build, but I didn't check if it works the same for reloading shotguns, top loaded weapons like the sks etc...

**Comment by christopher-talke** [comment]
Confirmed this is fixed
