### ISSUE TITLE
[Improvement] Profile-Selection missing when exposing the localhost

### ISSUE THREAD

**Issue by olli991** [ekky-llc/spt-raid-review#19]
I'm running a Fika-Server and tried what is working and what not.

I can get the Review-Server running and can also access it via localhost.

I've exposed the Ports 7828 and 7829 and can also access the site via Dyn-DNS domain. But here it's only showing "No profiles found..." on localhost I can see 3 profiles.

I'm a bit confused because to my understanding i am literally opening the same web-frontend :D

**Comment by olli991** [comment]
If i enter the profile path manually on exposed path i am getting this errors:
![image](https://github.com/ekky-llc/spt-raid-review/assets/55631413/29b94f1c-54bc-41aa-9baf-68785af98585)

**Comment by kenricv** [comment]
I had the same issue and managed to fix it by changing the hard-coded local address to my server's address: 

https://github.com/ekky-llc/spt-raid-review/blob/37123c78b3f6fbb832f2d0c21c32b6e937c3fbea/Server/src/Web/Client/src/api/api.tsx#L4
https://github.com/ekky-llc/spt-raid-review/blob/37123c78b3f6fbb832f2d0c21c32b6e937c3fbea/Client/mod.cs#L33-L34

**Comment by olli991** [comment]
So i assume i enter my dyn-dns address instead of 127.0.0.1 then.

Thats one solution.. but my small group is also syncing all the mods und stuff so they can play when my server isn't online. If i change this info in the config it wouldn't run for them anymore because then my server (which is off then) is hardcoded, right? :D

**Comment by christopher-talke** [comment]
Just merged a pull request from RavenX8; that should fix this, I'll upload 0.0.4 once I've finalised my changes to get map layers and maps lab loading again.
