### ISSUE TITLE
[Bug] When viewing map play back controls are off the screen

### ISSUE THREAD

**Issue by b00kz22** [ekky-llc/spt-raid-review#21]
When I open view map on Chrome the controls to play, stop, go faster, etc. are off the screen and there is no scross bar to scroll down and see them. I need to zoom the while window out to see them and control the map.

**Comment by christopher-talke** [comment]
**Thanks @b00kz22!**

- What do you set your zoom in order to see the playback?
- Any particular maps this happens on?

**If you have a moment, can you send me your data and profile files, and upload them here**

- \user\mods\raid_review__0.0.1\data
- \user\profiles\*

**Comment by christopher-talke** [comment]
Closing issue, solved in Dev branch. Will be in the next update, thanks for taking the time to report @b00kz22
