### ISSUE TITLE
Proper way to uninstall?

### ISSUE THREAD

**Issue by RebeliusGaming** [ekky-llc/spt-raid-review#43]
Hello.
I get no info. I can access the mod webpage, and I can see the profiles, but not a single raid has any info.
I read somewhere that this is due to having SAIN installed. 
I prefer to uninstall raid review untill it can work together

Can you tell me the proper way to uninstall?

Thank you!

**Comment by christopher-talke** [comment]
Hi Mate, 

Same as any other mod, just delete the files from the `/user/mods` folder and the `/BepInEx/plugins` folder.

Are you running SAIN, and if so which version. It does require SAIN v2.3.3 or later.

Did you play any raids with the mod installed?

**Comment by RebeliusGaming** [comment]
I have SAIN 2.2.4. Im gonna update and check.
I played more than 10 raids.

Thnaks for the answer

**Comment by RebeliusGaming** [comment]
Working. Ty
